version: '3.8'

services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
    networks:
      - devnet

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:5001"
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    networks:
      - devnet

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3001"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - devnet

volumes:
  mongo_data:

networks:
  devnet:
